// File: C.v
// Generated by MyHDL 0.10
// Date: Fri May 10 17:13:38 2019


`timescale 1ns/10ps

module C (
    out,
    x,
    a,
    clock,
    reset
);


output [31:0] out;
reg [31:0] out;
input [31:0] x;
input [31:0] a;
input clock;
input reset;

wire [31:0] e_0;
reg [31:0] e_1;
reg [31:0] e_2;

assign e_0 = 32'd23456297;


always @(posedge clock, negedge reset) begin: C_S
    if (reset == 0) begin
        e_2 <= 56456;
        e_1 <= 43017;
        out <= 0;
    end
    else begin
        e_1[32-1:16] <= a[32-1:16];
        e_2[32-1:16] <= a[16-1:0];
        out <= (($signed({1'b0, x}) * ($signed({1'b0, e_1}) + ($signed({1'b0, e_2}) * ($signed({1'b0, x}) - 32'h1)))) + e_0);
    end
end

endmodule
